### ISSUE TITLE
TinyMCE rich text editor not visible on model custom block

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/tinymce#19]
With TinyMCE configured for filtered html go to any layout, for example home page layout, in any region add a block and select "Custom block". The Block content area appears without the Rich Text Editor bar, whereas it does appear with cke4.

**Comment by indigoxela** [comment]
@izmeez many thanks for reporting. :+1:

That's a bit tricky, the layout dialog (iframe) opens an image dialog (iframe)...

However, it's only the image *paste handler* causing problems and the problem only happens, if *asset aggregation is off*, so it seems OK, to just turn pasting off for this special case. Image handling besides drag-n-drop works just fine.
The paste handler will still work fine in layouts as long as aggregation is on (admin/config/development/performance - " Aggregate JavaScript files".

Should be fixed in latest commit.

**Comment by izmeez** [comment]
You are right. I forgot I had turned aggregation off while making some theme changes. When I turn aggregation on the TinyMCE editor appears in layout > Add custom block. I'll have to checkout the latest commit to test it. Thanks.

**Comment by izmeez** [comment]
I have confirmed the latest commits fix the issue, works when js aggregation is on or off, and include a nice description. Thank you.

**Comment by indigoxela** [comment]
@izmeez many thanks for testing and confirming. :+1:
